// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/5/2026, 9:32:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/josaf/Desktop/Projectes/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/sections/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/josaf/Desktop/Projectes/Portfolio/composables/**/*.{js,ts,mjs}","C:/Users/josaf/Desktop/Projectes/Portfolio/utils/**/*.{js,ts,mjs}","C:/Users/josaf/Desktop/Projectes/Portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josaf/Desktop/Projectes/Portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;